### ISSUE TITLE
Dataset Processing

### ISSUE THREAD

**Issue by ziwei-cui** [kbressem/gpt4-structured-reporting#2]
Have you processed the MIMIC dataset? If so, is it convenient to tell me?

**Comment by kbressem** [comment]
No. You can find a notebook that guides you how to process the data in this repository. However, processing all 300k texts is costly. 

As it is a simple task you can use GPT 3.5 instead of GPT 4. This will be much cheaper and also faster but should still give good results. I would expect the costs to be between 100-200$ for processing all mimic texts.
